name: 'alpine-pandoc-hugo'
description: 'Alpine Linux with Pandoc and Hugo'
inputs:
  make-target:
    description: 'makefile target to run'
    required: true
    default: 'make'
runs:
  using: 'docker'
  image: 'ghcr.io/compilerbau/alpine-pandoc-hugo:latest'
  args:
    - export DOCKER=false; ${{ inputs.make-target }}
