##########################################################################
#
##########################################################################

#-------------------------------------------------------------------------
# Tools
#-------------------------------------------------------------------------
## Define tools to process various types of source files. By default, a
## custom Docker image will be used. To create this image, run:
## make create-docker-image
##
## Launching tools via a Docker container: make TARGET
## Launch the tools directly:              export DOCKER=false; make TARGET
##
## Note: LaTeX needs to be called in the folder of the .tex file to
## be processed. In the target "$(ALGORITHM)", the variable "$<" is            <--- Rename target
## set to the current .tex file (incl. path in the working directory).
## Therefore, the working directory for the Docker container is set
## to the folder of the current .tex file. When called directly, we
## need to first change-dir to this folder.
ifneq ($(DOCKER), false)
PANDOC = docker run --rm -i -v "$(shell pwd):/data" -w "/data"          -u "$(shell id -u):$(shell id -g)" --entrypoint="pandoc" alpine-pandoc-hugo
HUGO   = docker run --rm -i -v "$(shell pwd):/data" -w "/data"          -u "$(shell id -u):$(shell id -g)" --entrypoint="hugo"   alpine-pandoc-hugo
DOT    = docker run --rm -i -v "$(shell pwd):/data" -w "/data"          -u "$(shell id -u):$(shell id -g)" --entrypoint="dot"    alpine-pandoc-hugo
LATEX  = docker run --rm -i -v "$(dir $(realpath $<)):/data" -w "/data" -u "$(shell id -u):$(shell id -g)" --entrypoint="latex"  alpine-pandoc-hugo
else
PANDOC = pandoc
HUGO   = hugo
LATEX  = cd $(dir $<) && latex
DOT    = cd $(dir $<) && dot
endif

## Data-Dir: Path to the Git submodule of Pandoc-Lecture
## Resource-Path: Where to search for bib files and other resources?
##
## Note: If Pandoc is used via a Docker container, DATADIR must be the
## working directory or a subdirectory, as the working directory will
## be mounted into the Docker container! References to a parent directory
## of the working directory therefore will not work when using a Docker
## container!
PANDOC_DIRS = --data-dir=pandoc --resource-path=".:pandoc"

## Define options for generating images from ".tex" files
LATEX_ARGS = -shell-escape

## Define options for generating images from ".dot" files
DOT_ARGS = -Tpng

## Define options to be used by Hugo
## local.yaml allows to override settings in config.yaml
HUGO_ARGS = --config config.yaml,$(wildcard local.yaml)

#-------------------------------------------------------------------------
# I/O Directories
#-------------------------------------------------------------------------

## Top level folder for source files
SRC_DIR = markdown

## Top level folder for output files (input for Hugo)
OUTPUT_DIR = content

## Output folder generated by Hugo
HUGO_OUTPUT_DIR = docs

## Folder for generated PDF files
PDF_DIR = pdf

#-------------------------------------------------------------------------
# Helper lists
#-------------------------------------------------------------------------

## TeX files and their respective image files
TEX_SOURCES = $(shell find $(SRC_DIR) -type f -iname '*.tex')
TEX_TARGETS = $(patsubst $(SRC_DIR)/%.tex,$(OUTPUT_DIR)/%.png, $(TEX_SOURCES))

## Dot files and their respective image files
DOT_SOURCES = $(shell find $(SRC_DIR) -type f -iname '*.dot')
DOT_TARGETS = $(patsubst $(SRC_DIR)/%.dot,$(OUTPUT_DIR)/%.png, $(DOT_SOURCES))

## Standalone image files
## Note: The list of standalone image files is defined in a somewhat
## roundabout way in case there are image files present that have been
## generated manually from tex or dot source files.
## 	1. Find all existing png-files
## 	2. filter out files that have been generated from tex or dot files
##	(the simple expansion with ':=' is important here because we use the
##	same variable on both sides. Using a recursive expansion with '='
##	would result in an error.)
PNG_SOURCES  = $(shell find $(SRC_DIR) -type f -iname '*.png')
PNG_SOURCES := $(filter-out $(TEX_SOURCES:.tex=.png) $(DOT_SOURCES:.tex=.png), $(PNG_SOURCES))
PNG_TARGETS  = $(PNG_SOURCES:$(SRC_DIR)%=$(OUTPUT_DIR)%)

## Relative paths of all 'images' folders under $(SRC_DIR). Used to
## define phony targets that bundle generating all image files associated
## with that folder.
IMAGE_FOLDERS = $(patsubst $(SRC_DIR)/%,%,$(shell find $(SRC_DIR) -type d -iname 'images'))

## All target for image files
IMAGE_TARGETS = $(TEX_TARGETS) $(DOT_TARGETS) $(PNG_TARGETS)

#-------------------------------------------------------------------------
# Special files
#-------------------------------------------------------------------------

## Readings data template
READINGS = data/readings.yaml
BIBTEX   = cb.bib

## Create readings data template
$(READINGS): $(BIBTEX)
	$(PANDOC) -s -f biblatex -t markdown $< -o $@

#-------------------------------------------------------------------------
# Rules/Targets
#-------------------------------------------------------------------------

## Clean up
.PHONY: clean
clean:
	rm -rf $(OUTPUT_DIR)

## Clean up intermidiate latex files
.PHONY: latex-clean
latex-clean:
	rm -f $(shell find $(SRC_DIR) -type f \( -iname "*.aux" -o -iname "*.dvi" -o -iname "*.log" -o -iname "*.ps" \))

## Build Docker image "alpine-pandoc-hugo"
#.PHONY: create-docker-image
#create-docker-image:
#	cd .github/actions/alpine-pandoc-hugo && make clean all

## Create images from tex files
$(TEX_TARGETS): $(OUTPUT_DIR)%.png: $(SRC_DIR)%.tex
	mkdir -p $(dir $@)
	$(LATEX) $(LATEX_ARGS) $(notdir $<)
	cp $(<:.tex=.png) $@

## Create images from dot files
$(DOT_TARGETS): $(OUTPUT_DIR)%.png: $(SRC_DIR)%.dot
	mkdir -p $(dir $@)
	$(DOT) $(DOT_ARGS) $< -o $@

## Copy standalone image files
$(PNG_TARGETS): $(OUTPUT_DIR)%: $(SRC_DIR)%
	mkdir -p $(dir $@)
	cp $< $@

## TODO: Explain secondary expansion (what and why)
.SECONDEXPANSION:

## TODO: Explain how this rule works
.PHONY: $(IMAGE_FOLDERS)
$(IMAGE_FOLDERS): $$(filter $(OUTPUT_DIR)/$$@/%, $(IMAGE_TARGETS))
