name: HUGO
on:
  # push on master branch: build gh-page
  push:
    branches: [master]
  # manually triggered: build gh-page
  workflow_dispatch:


jobs:
  # build gh-page
  gh-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Pull docker image
        run: |
          docker pull ghcr.io/compilerbau/alpine-pandoc-hugo:latest

      - name: Build website
        uses: ./.github/actions/alpine-pandoc-hugo
        with:
          make-target: 'make web'

      - name: Publish website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/
          force_orphan: true
